spring:
  application:
    name: demo-project
jwt:
  secret: pX9i4m6wh9lluziQ02SDo7dtUhvK+wSQ++X4h/zCuwU= # {JWT_SECRET_KEY} 환경변수로 변경
  token:
    access-expiration: 3600000 # 1 hour
    refresh-expiration: 604800000 # 7 days
  issuer: demo-project