spring:
  application:
    name: demo-project
  datasource:
    url: jdbc:h2:file:./data/h2/demo;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;AUTO_SERVER=TRUE;AUTO_SERVER_PORT=9092
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  h2:
    console:
      enabled: true
      path: /h2-console
      
jwt:
  secret: pX9i4m6wh9lluziQ02SDo7dtUhvK+wSQ++X4h/zCuwU= # {JWT_SECRET_KEY} 환경변수로 변경
  token:
    access-expiration: 3600000 # 1 hour
    refresh-expiration: 604800000 # 7 days
  issuer: demo-project